repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

# black
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--config, pyproject.toml]

# flake8
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--config, .flake8]

# isort
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--sp, setup.cfg]
