# Generated by Django 3.1.7 on 2021-03-26 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210326_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='date',
            field=models.DateTimeField(auto_created=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='returnmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
