# Generated by Django 3.1.7 on 2021-03-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210326_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
